---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "konflux"
  name: fips-operator-check
spec:
  description: >-
    Checks operator bundle image builds for FIPS compliance using the check-payload tool.
  params:
    - name: image-digest
      description: Image digest to scan.
    - name: image-url
      description: Image URL.
  results:
    - name: TEST_OUTPUT
      description: Tekton task test output.
      value: $(steps.fips-operator-check-step-action.results.TEST_OUTPUT)
    - name: IMAGES_PROCESSED
      description: Images processed in the task.
      value: $(steps.fips-operator-check-step-action.results.IMAGES_PROCESSED)
  steps:
    - name: fips-operator-check-step-action
      computeResources:
        limits:
          memory: 512Mi
          cpu: 200m
        requests:
          memory: 256Mi
          cpu: 100m
      ref:
        name: fips-operator-check-step-action
      params:
        - name: image-digest
          value: $(params.image-digest)
        - name: image-url
          value: $(params.image-url)
